baseURL = 'https://recipedumper.paperministry.xyz/'
languageCode = 'en-us'
title = 'Recipes'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "github.com/GrantBirki/dario"
    version = "main"
